#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
Take the 'changes.py' file generated by 'average_compatibility.py' to patch
the database in order to not change average in the past when
changing the average formula.
"""

import changes

for table, col_id, line_id, dummy_perfect, old, dummy_new in changes.changes:
    print(table)
    year, semester, ue = table.split('/')
    with open("../DB/Y%s/S%s/%s.py" % (year, semester, ue), "a",
              encoding = "utf-8") as f:
        f.write("cell_change(0,'%s','%s',%s, '20161111111111')\n"
                % (col_id, line_id, repr(old)))
        f.write("comment_change(0,'%s','%s','Fixed!')\n" % (col_id, line_id))
