#!/bin/sh
# -*- sh -*-

export NODE_MODULE_CONTEXTS=1
export TZ=GMT-2

for NODE in nodejs node
do
    if [ -x $(which $NODE) ]
    then
	exec $NODE "$@"
    fi
done
echo "You need to install 'nodejs' in order to make regression tests" >&2
exit 1

