#!/bin/sh
# -*- sh -*-

export TRANSLATOR=RapydScript/bin/rapydscript

if [ ! -x $TRANSLATOR ]
then
    make translator
fi >&2

if [ -f $2 ]
then
    mv $2 $2~
fi

echo "Python translation to JavaScript: $1"
sed 's/yield/YIELD/' $1 |
tee xxx.debug |
./my_nodejs $TRANSLATOR --prettify --bare >$2

if [ ! -s $2 ]
then
    mv $2~ $2 # Restore corrupted file
    exit 1
fi
