#!/bin/sh
# -*- sh -*-

export TRANSLATOR=RapydScript/bin/rapydscript

if [ ! -x $TRANSLATOR ]
then
    echo "==============================================================="
    echo "RapydScript not installed: no Python to JavaScript translation"
    echo "You are using the staticaly translated JS from the tarball"
    echo "To install the translator, run:"
    echo ""
    echo "  (cd PYTHON_JS ; make translator)"
    echo ""
    echo "You need to install 'nodejs' in order to make regression tests"
    echo "==============================================================="
    exit 1
fi >&2

if [ -f $2 ]
then
    mv $2 $2~
fi

echo "Python translation to JavaScript: $1"
sed 's/yield/YIELD/' $1 |
tee xxx.debug |
./my_nodejs $TRANSLATOR --prettify --bare >$2

if [ ! -s $2 ]
then
    mv $2~ $2 # Restore corrupted file
    exit 1
fi
