#!/bin/sh
# -*- ksh -*-

# Arguments : DB et BACKUP_DB

DO() { echo $* ; }
DO() { eval $* ; }

for D in "$@"
do
  for F in $D/Y*/S*/referents.py
  do
    NEW_F=$(echo $F | sed 's/referents.py/referents_students.py/')
    if [ ! -f "$NEW_F" ]
    then
      DO mv $F $NEW_F
      DO rm "$F"c
    fi
  done
done

  
  
