#!/bin/sh

# Do not use this

set -e

echo 'Destroy test'

rm -r DBtest/* BACKUP_DBtest/* DBtest BACKUP_DBtest || true

ln -s $HOME/Trash/TOMUSS_DB DBtest
ln -s $HOME/Trash/BACKUP_TOMUSS_DB BACKUP_DBtest

echo 'Copy current'

ssh tomuss@tomus710 'cd production/DB; tar --exclude="*.pyc" --exclude="*~" -cf - .' |
(cd DBtest ; tar -xvf -)


echo 'Copy backup'

cp -a DBtest/* BACKUP_DBtest
