#!/bin/sh
# -*- ksh -*-

LOGS=LOGS/[ST]*/[0-9][0-9][0-9][0-9]-*[0-9]

echo "Remove old logs"
find $LOGS            -type f -mtime +200 -exec rm {} +

echo "Compress logs"
find $LOGS            -type f -mtime +2 ! -name "*.bz2"  -exec bzip2 -v -9 {} +

echo "Remove old backtraces"
find LOGS/BACKTRACES/ -maxdepth 1 -type d -mtime +60  -exec rm -r {} +

echo "Remove old table in 2008/Tests"
mkdir Trash/$(date +"%Y%m%d")
TRASH="Trash/$(date +"%Y%m%d")/2008TestLogJanitor"
mkdir "$TRASH"
find DB/Y2008/STest/ -type f -mtime +400 ! -name '__init__.py' -exec mv {} "$TRASH" \;

echo "Remove empty indexes in the database"
find DB/LOGINS -size 2c \( -name index \) -exec rm {} +
find DB/LOGINS -depth -type d -empty -exec rmdir {} +

echo "Search strange login names, do not delete them"
ls -d DB/LOGINS/*/*[!-_.a-zA-Z0-9]*

echo "Remove uploaded file backup older than a year"
find UPLOAD/ -mtime +400 -name "*~" -exec rm {} +


echo "Remove dandling rsskey to login index"
for I in DB/RSSLOGINS/*/*
do
    J="$(cat $I)"
    if [ ! -f DB/LOGINS/"$(echo "$J" | cut -c 1-3)"/"$J"/rsskey ]
    then
	echo "Remove $I -> $J"
	rm "$I"
    fi
done

echo "Launch LOCAL/log_janitor"
if [ -x LOCAL/log_janitor ]
    then
    LOCAL/log_janitor
    fi


