#!/bin/sh
# -*- ksh -*-

LOGS=LOGS/[ST]*/[0-9][0-9][0-9][0-9]-*[0-9]

# Remove old logs.
find $LOGS            -type f -mtime +200 -exec rm {} \;

# Compress logs
find $LOGS            -type f -mtime +2 ! -name "*.bz2"  -exec bzip2 -v -9 {} \;

# Remove old backtraces.
find LOGS/BACKTRACES/ -type d -mtime +60  -exec rm -r {} \;

# Remove old tests :
mkdir Trash/$(date +"%Y%m%d")
TRASH="Trash/$(date +"%Y%m%d")/2008TestLogJanitor"
mkdir "$TRASH"
find DB/Y2008/STest/ -type f -mtime +400 ! -name '__init__.py' -exec mv {} "$TRASH" \;


