#!/bin/sh
# -*- ksh -*-

echo "Start crypted backup the $(date)"
SCRIPTS/sauvegarde >LOGS/xxx_crontab_night_job.sauvegarde 2>&1

echo "Start compute access statistics the $(date)"
SCRIPTS/access.py  >LOGS/xxx_crontab_night_job.access 2>&1

echo "Start compute student bilan the $(date)"
SCRIPTS/bilan.py >LOGS/xxx_crontab_night_job.bilan 2>&1

echo "Start database mirroring check the $(date)"
SCRIPTS/mirror_check >LOGS/xxx_crontab_night_job.mirror_check 2>&1

echo "Start updating database from external sources the $(date)"
cd LOCAL
make >../LOGS/xxx_crontab_night_job.local 2>&1

echo "End of night job the $(date)"


cd ..
M=''
for I in LOGS/xxx_crontab_*
do
  N=$(expr $(grep -ic traceback $I) - $(grep -ic shutdown $I))
  if [ "$N" != 0 ]
  then
    M="$M $I"
  fi
done

if [ '' != "$M" ]
then
  python -c "
import SCRIPTS.tomuss_init
import utilities 
import configuration

utilities.send_mail(configuration.maintainer,
                    'BUG night job : $M', 'All in subject')"
fi
