#!/bin/sh
# -*- ksh -*-
# Remove some unused columns from tables.
# Needs to stop the server

exit 1

cd DB/Y2008/SAutomne

f() {
  N=$(grep -c $1 $2)
  case $N in
    0) ;;
    1) echo $2 remove $N $1
       grep -v $1 <$2 >xxx && diff xxx $2
       ;;
    *) # echo $2 problem $N $1
       # sed "s/column_change(0,'$1','S../&Detruite/" <$2 >xxx && echo mv xxx $2
       ;;
  esac
}

FILES="UE-MAT1002L.py"

for I in $FILES
do
  for C in $(grep <$I '^column_change' | cut -d',' -f2 | sort -u)
  do
    f $C $I
  done
done
