#!/bin/sh
# -*- ksh -*-
# Remove some unused columns from tables.
# Needs to stop the server

exit 1

cd DB/Y2008/SAutomne

remove_col() {
  N=$(grep -c $1 $2)
  case $N in
    0) ;;
    1) echo $2 remove $N $1
       grep -v $1 <$2 >xxx && mv xxx $2
       ;;
    *) echo $2 problem $N $1
       sed "s/column_change(0,'$1','S../&Detruite/" <$2 >xxx && diff mv xxx $2
       ;;
  esac
}

rename_col() {
  echo 'rename' $1 $2 $3
  sed "s/column_change(0,'$1','[^']*'/column_change(0,'$1','$3'/" <$2 >xxx && diff mv xxx $2
      } 


# enlève colonne 0_h de MAT2

for I in UE-MAT2*.py
do
  remove_col "0_h" "$I"
done

# Renomme colonne 0_g de MAT1 pour quelle s'appelle S3P

for I in UE-MAT1*.py
do
  rename_col "0_h" "$I" "S3P"
done

