all: eye.png butterflynet.png

eye.png:eye.svg
	inkscape --export-png=$@ --export-area-drawing --export-width=16 $?

butterflynet.png:butterflynet.svg
	inkscape --export-png=$@ --export-area-drawing --export-width=32 $?
clean:
	# Nothing to do ?
